services:
  - type: static_site # <-- This is the corrected line
    name: enginuity-alpha-frontend
    env: static
    buildCommand: "npm run build"
    publishDir: "dist"
    headers:
      - path: "/*"
        values:
          - key: Content-Security-Policy
            value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"
          - key: X-Frame-Options
            value: "SAMEORIGIN"
          - key: Referrer-Policy
            value: "strict-origin-when-cross-origin"
          - key: Permissions-Policy
            value: "camera=(), microphone=(), geolocation=()"
