services:
  # This defines only your frontend static site service
  - type: static
    name: enginuity-alpha-frontend # A name for your service on Render
    # Tells Render where your frontend project is located
    rootDir: frontend/chat-front-end 
    env: static
    buildCommand: "npm run build"
    publishDir: "dist"
    headers:
      - path: "/*"
        values:
          - key: Content-Security-Policy
            value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"
          - key: X-Frame-Options
            value: "SAMEORIGIN"
          - key: Referrer-Policy
            value: "strict-origin-when-cross-origin"
          - key: Permissions-Policy
            value: "camera=(), microphone=(), geolocation=()"
