services:
  - type: web
    name: chat-frontend
    env: static
    
    # Tells Render to look inside the 'chat-front-end' folder from this location
    rootDir: chat-front-end
    
    # Build and publish commands
    buildCommand: npm install && npm run build
    staticPublishPath: dist

    # The security headers configuration
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: "geolocation=(), microphone=(), camera=()"
