# This file is located at /frontend/render.yaml

services:
  - type: static
    name: chat-frontend # You can name this whatever you like
    env: static
    
    # ⬇️ This is the crucial line you need to add.
    # It tells Render to run commands from inside this folder.
    rootDir: chat-front-end
    
    # Build commands for a standard Vite/React app
    buildCommand: 'npm install && npm run build'
    staticPublishPath: 'dist'

    # The security headers you need
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: "geolocation=(), microphone=(), camera=()"
