services:
  # This defines your frontend service
  - type: web # <-- Corrected type based on documentation
    name: enginuity-alpha-frontend
    runtime: static # <-- Required for a static site
    rootDir: frontend/chat-front-end
    buildCommand: "npm run build"
    publishDir: "dist"
    headers:
      - path: "/*"
        values:
          - key: Content-Security-Policy
            value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"
          - key: X-Frame-Options
            value: "SAMEORIGIN"
          - key: Referrer-Policy
            value: "strict-origin-when-cross-origin"
          - key: Permissions-Policy
            value: "camera=(), microphone=(), geolocation=()"
